# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Warden < Formula
  desc "Audit your git repositories based on policy."
  homepage "https://RepoWarden.com"
  version "0.13.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/repowarden/cli/releases/download/v0.13.1/warden-v0.13.1-macos-amd64.tar.gz"
      sha256 "a203ed6e567abae626e5c05fa618345542084b35f06d942d8685a1771a9cafdb"

      def install
        bin.install "warden"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/repowarden/cli/releases/download/v0.13.1/warden-v0.13.1-macos-arm64.tar.gz"
      sha256 "c0a73ecc7c707659752607586eea7fd0222f15e0756d5a4cad0dec74ec113341"

      def install
        bin.install "warden"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/repowarden/cli/releases/download/v0.13.1/warden-v0.13.1-linux-amd64.tar.gz"
      sha256 "1c99b58cb2d3961d47d69d7b5510c2b4c13dd42f655b5d721b25fb329655bdb2"

      def install
        bin.install "warden"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/repowarden/cli/releases/download/v0.13.1/warden-v0.13.1-linux-arm64.tar.gz"
      sha256 "33e477e4329d946babcf5c9711d69a80650e3dad236fbea04881a7c293a2bb16"

      def install
        bin.install "warden"
      end
    end
  end

  test do
    system "#{bin}/warden", "help"
  end
end
